name: CI-Release

on:
  pull_request:
    types: [ opened, reopened ]
  push:
    branches:
      - main

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: build binary
        run: |
          docker build . -t builder
          docker run --rm -v ${PWD}:/project builder make -j$(nproc)
      - uses: actions/upload-artifact@master
        with:
          name: HBL Version
          path: "theme-manager.zip"
      - uses: actions/upload-artifact@master
        with:
          name: Aroma Version
          path: "theme-manager.wuhb"
